### ISSUE TITLE
[SUGGESTION] Change drop rate of the items

### ISSUE THREAD

**Issue by Brayman4k** [Erfurt92/MagicalJewelry#16]
Hi! Is it possible to decrease the drop % of the items? I added the mod in my modpack, but it kinda broke some XP farms, since the drops were so high that we ran out of storage.

**Comment by Erfurt92** [comment]
Already possible, you can change it with a datapack, just make sure that you include the function, otherwise you won't get any usable items, here are the [loottable](https://github.com/Erfurt92/MagicalJewelry/blob/1.20.x/src/generated/resources/data/magicaljewelry/loot_tables/entities/hostile_jewel_drops.json)  used by regular hostile mobs
