### ISSUE TITLE
[BUG] Game crashed

### ISSUE THREAD

**Issue by SissyTrashQueen** [Erfurt92/MagicalJewelry#3]
**Versions:**
* Magical Jewelry: magicaljewelry-1.15.2_1.0.4
* Curios: curios-FORGE-1.15.2-2.0.2.4
* Forge: 31.2.0

**Describe the bug**
I went into creative mode, picked up the rings and jewels, equipped one on its curios slot and it crashed. I guess I'm not supposed to do that lol

**Additional context**
Crash Report: [Here](https://gist.github.com/slard3/d77461b0d240f7626aabd7a27e44a235)

**Comment by SissyTrashQueen** [comment]
Because I don't want to make two issues, here I go again: Do you have plans to add more effects to the jewels, like the [Rings of Ascension Mod](https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension)? Also, if I have two of the same normal/legendary potion effects equipped, do you think those could stack (say I have a Fire Resistance I effect, if I equip two of these curios, it could give me a Fire Resistance II)?

**Comment by Erfurt92** [comment]
- Fixed in version 1.0.5 - I forgot a check. Jewel from the ItemGroup, doesn't do anything, so I completely forgot about them. I do have a plan to give random rarity and effects when you pick them up from creative. But not something I have had the time to work on yet.
- I'm not going to add any effects that's not in vanilla, Would be a lot of work if I had to add compatibility for other mods.
- Normal effects stack by default up to level 2, you can change that in config to be level 3 or have it so they doesn't stack. As for the Legendary effects, they stay at level 1, as there's no point in having them stacking, no difference between the levels for them.
